
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  # Uncomment to disable the `avoid_print` rule

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
  plugins:
    - custom_lint
